title: "llm-contracts"
description: "Stop trusting LLM output. Start validating it. Developer-first framework for catching AI mistakes before they reach production."

# Minimal GitHub Pages setup - no theme
url: https://maxamed.github.io/llm-contract
baseurl: ""

# Basic plugins only
plugins:
  - jekyll-feed

# Basic settings
markdown: kramdown
highlighter: rouge

# Author
author: "Mohamed Jama" 