title: llm-contracts v1.0.0
description: Developer-first framework for validating LLM-generated outputs - Now available on PyPI!

theme: minima

# Minima theme configuration
minima:
  # Use custom navigation ordering
  header_pages:
    - index.md
    - getting-started.md
    - features.md
    - examples.md
    - frontend.md
    - api-reference.md  
    - whitepaper.md
    - solidarity.md
    - installation.md
    - roadmap.md 