title: "llm-contracts"
description: "Stop trusting LLM output. Start validating it. Developer-first framework for catching AI mistakes before they reach production."

# Use most reliable GitHub Pages theme
theme: minima

# Site URL
url: https://maxamed.github.io/llm-contract
baseurl: ""

# Author
author:
  name: "Mohamed Jama"
  email: "mohamed.jama@gmail.com"

# GitHub repository  
repository: "Maxamed/llm-contract"

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Minima theme settings
minima:
  skin: dark

# Code highlighting
highlighter: rouge
markdown: kramdown

# SEO
lang: en-US

# Build settings
sass:
  style: compressed 